//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Praksa_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {

        public int id { get; set; }

        [Display(Name="Marka")]
        public string carMake { get; set; }
        public string carType { get; set; }
        public Nullable<int> engineNo { get; set; }
        public string chasisNo { get; set; }
        public string power { get; set; }
        public string fuel { get; set; }
        public Nullable<int> manYear { get; set; }
    }
}
