//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praksa_V2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cars
    {
        public Cars()
        {
            this.Positions = new HashSet<Positions>();
        }
        [Display(Name="ID")]
        public int id { get; set; }
        [Display(Name = "Marka")]
        public string carMake { get; set; }
        [Display(Name = "Tip vozila")]
        public string carType { get; set; }
        [Display(Name = "Broj motora")]
        public Nullable<int> engineNo { get; set; }
        [Display(Name = "Broj šasije")]
        public string chasisNo { get; set; }
        [Display(Name = "Snaga motora")]
        public string power { get; set; }
        [Display(Name = "Vrsta goriva")]
        public string fuel { get; set; }
        [Display(Name = "Godina proizvodnje")]
        public Nullable<int> manYear { get; set; }
    
        public virtual ICollection<Positions> Positions { get; set; }
    }
}
