//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praksa_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Positions
    {
        public int id_position { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string status { get; set; }
        public int id { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
